### ISSUE TITLE
JSnappy

### ISSUE THREAD

**Issue by ChristianSchwarz** [ning/jvm-compressor-benchmark#5]
There is another pure Java implementation that could be included in the benchmark, its called JSnappy.  A nice feature is a optional multi thread decompressor. It would be intresting if it is faster than -> "https://github.com/dain/snappy".

Link: http://code.google.com/p/jsnappy/

**Comment by cowtowncoder** [comment]
Will close this one, but will re-evaluate implementations included: likely to use Snappy from aircompress or apache common-compress.
